// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package applicationServer;

public final class CentralServerImpl_Stub
    extends java.rmi.server.RemoteStub
    implements applicationServer.CentralServer, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_addBenutzerNameToUser_0;
    private static java.lang.reflect.Method $method_delUser_1;
    private static java.lang.reflect.Method $method_getMyApplicationServer_2;
    
    static {
	try {
	    $method_addBenutzerNameToUser_0 = applicationServer.CentralServer.class.getMethod("addBenutzerNameToUser", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	    $method_delUser_1 = applicationServer.CentralServer.class.getMethod("delUser", new java.lang.Class[] {java.lang.String.class});
	    $method_getMyApplicationServer_2 = applicationServer.CentralServer.class.getMethod("getMyApplicationServer", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public CentralServerImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of addBenutzerNameToUser(String, String)
    public void addBenutzerNameToUser(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_addBenutzerNameToUser_0, new java.lang.Object[] {$param_String_1, $param_String_2}, -7793791501558032642L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of delUser(String)
    public void delUser(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_delUser_1, new java.lang.Object[] {$param_String_1}, 3258200417619323711L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getMyApplicationServer(String, String)
    public java.lang.String getMyApplicationServer(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getMyApplicationServer_2, new java.lang.Object[] {$param_String_1, $param_String_2}, 4105297340101121645L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
